spring :
  application :
     name : order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order-service
    username: hamza
    password: hamza911code
  jpa:
    hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
        hibernate:
          format_sql: true
server:
  port: 8081
