spring :
  application :
    name : product-service
  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/products-service?authSource=admin
eureka:
  client:
    serviceUrl:
      defaultZone : http://localhost:8761/eureka/

